# Generated by Django 4.2.7 on 2023-11-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepage', '0002_track_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='art',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='track',
            name='link',
            field=models.TextField(max_length=250),
        ),
    ]
