# Generated by Django 4.2.7 on 2023-11-18 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamepage', '0003_alter_track_art_alter_track_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='gamepage.game'),
        ),
    ]
