# Generated by Django 4.2.7 on 2023-11-18 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamepage', '0007_alter_game_id_gametrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamepage.game'),
        ),
        migrations.DeleteModel(
            name='GameTrack',
        ),
    ]
