# Generated by Django 4.2.7 on 2023-11-19 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamepage', '0009_gametrack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='art',
        ),
    ]
