# Generated by Django 4.2.7 on 2023-11-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepage', '0010_remove_track_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='passcode',
            field=models.CharField(default='ls8Fku', max_length=6),
        ),
        migrations.DeleteModel(
            name='GameTrack',
        ),
    ]
