# Generated by Django 4.2.7 on 2023-11-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepage', '0011_game_passcode_delete_gametrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='passcode',
            field=models.CharField(default='WtljN4', max_length=6),
        ),
    ]
